In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import re
plt.rcParams['font.family'] = 'AppleGothic'

pd.set_option('display.max_columns', None)

In [41]:
ubob = pd.read_excel('/Users/user/Documents/진행중 업무/WORKS Option Plus Ubob1.xlsx')
ubob

    회사이름   domainId    ncpId                   plan
0    NaN     138619  1611080     웍스 옵션 플러스 유밥(법정필수)
1    NaN     159879  2510345     웍스 옵션 플러스 유밥(법정필수)
2    NaN  300147427  2527033     웍스 옵션 플러스 유밥(법정필수)
3    NaN  300150843  2533929     웍스 옵션 플러스 유밥(법정필수)
4    NaN     156190  2581381     웍스 옵션 플러스 유밥(법정필수)
5    NaN     160601  2586373     웍스 옵션 플러스 유밥(법정필수)
6    NaN     177136  2607671     웍스 옵션 플러스 유밥(법정필수)
7    NaN      16215  2655199     웍스 옵션 플러스 유밥(법정필수)
8    NaN     159170  2656715     웍스 옵션 플러스 유밥(법정필수)
9    NaN     178073  2662610  웍스 옵션 플러스 유밥(법정필수+직무)
10   NaN     225570  2673067     웍스 옵션 플러스 유밥(법정필수)
11   NaN  300150510  2748659     웍스 옵션 플러스 유밥(법정필수)
12   NaN  300013796  2810265     웍스 옵션 플러스 유밥(법정필수)
13   NaN  300151311  2865615     웍스 옵션 플러스 유밥(법정필수)
14   NaN  300124267  2889200  웍스 옵션 플러스 유밥(법정필수+직무)
15   NaN  300045410  2920936     웍스 옵션 플러스 유밥(법정필수)
16   NaN  300069851  3019017  웍스 옵션 플러스 유밥(법정필수+직무)
17   NaN  300177769  3190058     웍스 옵션 플러스 유밥(법정필수)
18   NaN  300126306  3254324  웍스 옵션 플러스 유밥(법정필수+직무)
19   NaN  300146497  3328736     웍스 옵션 플러스 유밥(법정필수)
20   NaN  300159272  3379547     웍스 옵션 플러스 유밥(법정필수)
21   NaN  300160715  3385429  웍스 옵션 플러스 유밥(법정필수+직무)
22   NaN  300163020  3391461     웍스 옵션 플러스 유밥(법정필수)
23   NaN  300171589  3414194  웍스 옵션 플러스 유밥(법정필수+직무)
24   NaN  300171083  2543503     웍스 옵션 플러스 유밥(법정필수)
25   NaN  300013365  2552351     웍스 옵션 플러스 유밥(법정필수)
26   NaN  300150393  2688285     웍스 옵션 플러스 유밥(법정필수)
27   NaN  300108778  3180335     웍스 옵션 플러스 유밥(법정필수)
28   NaN  300150536  3195016     웍스 옵션 플러스 유밥(법정필수)
29   NaN  300140985  2527059     웍스 옵션 플러스 유밥(법정필수)
30   NaN     141346  2532398     웍스 옵션 플러스 유밥(법정필수)
31   NaN  300151262  2860996  웍스 옵션 플러스 유밥(법정필수+직무)
32   NaN  300150667  2865004     웍스 옵션 플러스 유밥(법정필수)
33   NaN  300147515  3095962     웍스 옵션 플러스 유밥(법정필수)
34   NaN  300143511  3319002     웍스 옵션 플러스 유밥(법정필수)
35   NaN  300147632  3335241     웍스 옵션 플러스 유밥(법정필수)
36   NaN     186955  2543653     웍스 옵션 플러스 유밥(법정필수)
37   NaN  300093496  3115000  웍스 옵션 플러스 유밥(법정필수+직무)
38   NaN  300136142  3240864     웍스 옵션 플러스 유밥(법정필수)
39   NaN  300140798  3304335  웍스 옵션 플러스 유밥(법정필수+직무)
40   NaN  300145879  3328525  웍스 옵션 플러스 유밥(법정필수+직무)

In [43]:
boa30 = pd.read_excel('/Users/user/Documents/진행중 업무/데이터/BOA/BOA(202406)new.xlsx')
boa31 = pd.read_excel('/Users/user/Documents/진행중 업무/데이터/BOA/BOA(202407)new.xlsx')
boa32 = pd.read_excel('/Users/user/Documents/진행중 업무/데이터/BOA/BOA(202408)new.xlsx')
boa33 = pd.read_excel('/Users/user/Documents/진행중 업무/데이터/BOA/BOA(202409)new.xlsx')
boa34 = pd.read_excel('/Users/user/Documents/진행중 업무/데이터/BOA/BOA(202410)new.xlsx')
boa35 = pd.read_excel('/Users/user/Documents/진행중 업무/데이터/BOA/BOA(202411)new.xlsx')

In [44]:
boa = pd.concat([boa30, boa31, boa32, boa33, boa34, boa35])
boa = boa[['NCP회원번호','회원명']]

In [47]:
boa = boa.drop_duplicates(subset = ['NCP회원번호'], keep='last')
boa = boa.rename(columns={'NCP회원번호': 'ncpId'})

In [49]:
ubob['ncpId'] = ubob['ncpId'].astype(str)
boa['ncpId'] = boa['ncpId'].astype(str)

map = pd.merge(ubob, boa, on='ncpId', how='left')

In [53]:
map['회사이름']=map['회원명']
map = map.drop('회원명',axis=1)
map

                     회사이름   domainId    ncpId                   plan
0               (주)트리플하이엠     138619  1611080     웍스 옵션 플러스 유밥(법정필수)
1               주식회사 디피허브     159879  2510345     웍스 옵션 플러스 유밥(법정필수)
2                     NaN  300147427  2527033     웍스 옵션 플러스 유밥(법정필수)
3             주식회사 씨앤디팩토리  300150843  2533929     웍스 옵션 플러스 유밥(법정필수)
4                   세기위더스     156190  2581381     웍스 옵션 플러스 유밥(법정필수)
5                 손봄 주식회사     160601  2586373     웍스 옵션 플러스 유밥(법정필수)
6         주식회사 와이엔컬쳐앤스페이스     177136  2607671     웍스 옵션 플러스 유밥(법정필수)
7             주식회사 삼성사이니지      16215  2655199     웍스 옵션 플러스 유밥(법정필수)
8             주식회사 블랙브라더스     159170  2656715     웍스 옵션 플러스 유밥(법정필수)
9                   비즈그리다     178073  2662610  웍스 옵션 플러스 유밥(법정필수+직무)
10             주식회사 포유컴퓨터     225570  2673067     웍스 옵션 플러스 유밥(법정필수)
11               주식회사티디에프  300150510  2748659     웍스 옵션 플러스 유밥(법정필수)
12          (주)골든에이지인터내셔널  300013796  2810265     웍스 옵션 플러스 유밥(법정필수)
13                  슬로우보이  300151311  2865615     웍스 옵션 플러스 유밥(법정필수)
14               주식회사 블록잼  300124267  2889200  웍스 옵션 플러스 유밥(법정필수+직무)
15                  이그나이트  300045410  2920936     웍스 옵션 플러스 유밥(법정필수)
16                    윤**  300069851  3019017  웍스 옵션 플러스 유밥(법정필수+직무)
17                    NaN  300177769  3190058     웍스 옵션 플러스 유밥(법정필수)
18             아이티무유 주식회사  300126306  3254324  웍스 옵션 플러스 유밥(법정필수+직무)
19         주식회사 코레스테틱스글로벌  300146497  3328736     웍스 옵션 플러스 유밥(법정필수)
20             주식회사 해피웨이브  300159272  3379547     웍스 옵션 플러스 유밥(법정필수)
21                    김**  300160715  3385429  웍스 옵션 플러스 유밥(법정필수+직무)
22           주식회사 이스포츠스코어  300163020  3391461     웍스 옵션 플러스 유밥(법정필수)
23  (주)티엠케이플랜트(TMK PLANT)  300171589  3414194  웍스 옵션 플러스 유밥(법정필수+직무)
24                    NaN  300171083  2543503     웍스 옵션 플러스 유밥(법정필수)
25                    NaN  300013365  2552351     웍스 옵션 플러스 유밥(법정필수)
26                  캠퍼스멘토  300150393  2688285     웍스 옵션 플러스 유밥(법정필수)
27                 DB저축은행  300108778  3180335     웍스 옵션 플러스 유밥(법정필수)
28          페트라빌자산운용 주식회사  300150536  3195016     웍스 옵션 플러스 유밥(법정필수)
29                    NaN  300140985  2527059     웍스 옵션 플러스 유밥(법정필수)
30                    NaN     141346  2532398     웍스 옵션 플러스 유밥(법정필수)
31                    NaN  300151262  2860996  웍스 옵션 플러스 유밥(법정필수+직무)
32                    NaN  300150667  2865004     웍스 옵션 플러스 유밥(법정필수)
33                    NaN  300147515  3095962     웍스 옵션 플러스 유밥(법정필수)
34                    NaN  300143511  3319002     웍스 옵션 플러스 유밥(법정필수)
35         주식회사 브이엘인베스트먼트  300147632  3335241     웍스 옵션 플러스 유밥(법정필수)
36                (주)트라이업     186955  2543653     웍스 옵션 플러스 유밥(법정필수)
37                  신성어패럴  300093496  3115000  웍스 옵션 플러스 유밥(법정필수+직무)
38                     유밥  300136142  3240864     웍스 옵션 플러스 유밥(법정필수)
39                    정**  300140798  3304335  웍스 옵션 플러스 유밥(법정필수+직무)
40                    NaN  300145879  3328525  웍스 옵션 플러스 유밥(법정필수+직무)

In [55]:
map.to_excel('/Users/user/Documents/진행중 업무/WORKS Option Plus Ubob1.xlsx',index=False)

In [57]:
ncd = pd.read_csv('/Users/user/Documents/진행중 업무/ncd_metering2.csv')

/var/folders/yj/y3b7nzyn7zv0l9bkqtj_37g40000gn/T/ipykernel_25018/3318143764.py:1: DtypeWarning: Columns (31,35,36,41,43,47,48,49,50) have mixed types. Specify dtype option on import or set low_memory=False.
  ncd = pd.read_csv('/Users/user/Documents/진행중 업무/ncd_metering2.csv')

In [61]:
ncd

,회원번호,회원그룹코드,회원그룹명,파트너사회원번호,청구유형코드,청구유형코드명,청구유형상세코드,청구유형상세코드명,인스턴스유형코드,인스턴스유형코드명,미터링유형코드,미터링유형코드명,계약번호,인스턴스번호,리전번호,리전명,계약상품일련번호,약정여부,요금,미터링일시,사용량,상품사이즈,상품갯수,이벤트사용량,사용량단위코드,사용량단위명,plan,member_id,calc_ymd,seller_id,regist_ymd,delete_ymd,leaveYn,domainRegistdate,paid_여부,전환여부,전환일,도메인유료구독상품,도메인유료구독상품개수,도메인구독상품,도메인구독상품개수,도메인WORKPLACE유료구독상세상품,도메인WORKPLACE유료구독상세상품개수,도메인WORKPLACE구독상세상품,도메인WORKPLACE구독상세상품개수,도메인유료구독상품_구분3,도메인구독상품_구분3,도메인WORKPLACE유료구독상세상품_구분3,도메인WORKPLACE구독상세상품_구분3,이전상품_Trial포함,Paid_이전상품,일요금(당일),일매출(당일)
0,296,INTL,내부회원,NaN,NWRPL,WORKPLACE (Deprecated),WPCBM,Basic,NWRPL,WORKPLACE (Deprecated),WPCBM,WORKPLACE Basic,4583767,5710058,1,Korea,5,N,4000.0,20230101,2.0,NaN,NaN,2.0,USR_CNT,사용자 수,APP_STD,296,2023.1.1,0,2023.1.1,2024.2.29,Y,2023.1.1,Y,NaN,NaN,APP_STD,1.0,APP_STD,1.0,"APP_STD, ATT_STD, FIN_STD",3.0,"APP_STD, ATT_STD, FIN_STD",3.0,경영지원,경영지원,"웍스 결재, 웍스 근태, 웍스 재무","웍스 결재, 웍스 근태, 웍스 재무",NaN,NaN,258.064516,258.064516
1,296,INTL,내부회원,NaN,NWRPL,WORKPLACE (Deprecated),WPCBM,Basic,NWRPL,WORKPLACE (Deprecated),WPCBM,WORKPLACE Basic,4583767,5710058,1,Korea,5,N,4000.0,20230101,2.0,NaN,NaN,2.0,USR_CNT,사용자 수,ATT_STD,296,2023.1.1,0,2023.1.1,2024.2.29,Y,2023.1.1,Y,NaN,NaN,APP_STD,1.0,APP_STD,1.0,"APP_STD, ATT_STD, FIN_STD",3.0,"APP_STD, ATT_STD, FIN_STD",3.0,경영지원,경영지원,"웍스 결재, 웍스 근태, 웍스 재무","웍스 결재, 웍스 근태, 웍스 재무",NaN,NaN,258.064516,258.064516
2,296,INTL,내부회원,NaN,NWRPL,WORKPLACE (Deprecated),WPCBM,Basic,NWRPL,WORKPLACE (Deprecated),WPCBM,WORKPLACE Basic,4583767,5710058,1,Korea,5,N,4000.0,20230101,2.0,NaN,NaN,2.0,USR_CNT,사용자 수,FIN_STD,296,2023.1.1,0,2023.1.1,2024.2.29,Y,2023.1.1,Y,NaN,NaN,APP_STD,1.0,APP_STD,1.0,"APP_STD, ATT_STD, FIN_STD",3.0,"APP_STD, ATT_STD, FIN_STD",3.0,경영지원,경영지원,"웍스 결재, 웍스 근태, 웍스 재무","웍스 결재, 웍스 근태, 웍스 재무",NaN,NaN,258.064516,258.064516
3,296,INTL,내부회원,NaN,NWRPL,WORKPLACE (Deprecated),WPCBM,Basic,NWRPL,WORKPLACE (Deprecated),WPCBM,WORKPLACE Basic,4583767,5710058,1,Korea,5,N,4000.0,20230102,2.0,NaN,NaN,2.0,USR_CNT,사용자 수,APP_STD,296,2023.1.2,0,2023.1.1,2024.2.29,Y,2023.1.1,Y,NaN,NaN,APP_STD,1.0,APP_STD,1.0,"APP_STD, ATT_STD, FIN_STD",3.0,"APP_STD, ATT_STD, FIN_STD",3.0,경영지원,경영지원,"웍스 결재, 웍스 근태, 웍스 재무","웍스 결재, 웍스 근태, 웍스 재무",NaN,NaN,258.064516,258.064516
4,296,INTL,내부회원,NaN,NWRPL,WORKPLACE (Deprecated),WPCBM,Basic,NWRPL,WORKPLACE (Deprecated),WPCBM,WORKPLACE Basic,4583767,5710058,1,Korea,5,N,4000.0,20230102,2.0,NaN,NaN,2.0,USR_CNT,사용자 수,ATT_STD,296,2023.1.2,0,2023.1.1,2024.2.29,Y,2023.1.1,Y,NaN,NaN,APP_STD,1.0,APP_STD,1.0,"APP_STD, ATT_STD, FIN_STD",3.0,"APP_STD, ATT_STD, FIN_STD",3.0,경영지원,경영지원,"웍스 결재, 웍스 근태, 웍스 재무","웍스 결재, 웍스 근태, 웍스 재무",NaN,NaN,258.064516,258.064516
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26806048,3455107,GEN,Ncloud온라인회원,NaN,WORK2,NAVER WORKS,CORE_TRIAL_USER_CNT,웍스 코어 체험판,WORK2,NAVER WORKS,CORE_TRIAL_USER_CNT,웍스 코어 체험판,18551495,101818808,1,Korea,2,N,0.0,20250108,1.0,NaN,NaN,1.0,USR_CNT,사용자 수,COR_T,3455107,2025.1.8,0,2025.1.8,NaN,N,2025.1.8,N,N,NaN,NaN,0.0,COR_T,1.0,NaN,NaN,NaN,NaN,NaN,웍스코어,NaN,NaN,NaN,NaN,0.000000,0.000000
26806049,3455110,GEN,Ncloud온라인회원,NaN,WORK2,NAVER WORKS,CORE_TRIAL_USER_CNT,웍스 코어 체험판,WORK2,NAVER WORKS,CORE_TRIAL_USER_CNT,웍스 코어 체험판,18551531,101819165,1,Korea,2,N,0.0,20250108,1.0,NaN,NaN,1.0,USR_CNT,사용자 수,COR_T,3455110,2025.1.8,0,2025.1.8,NaN,N,2025.1.8,N,N,NaN,NaN,0.0,COR_T,1.0,NaN,NaN,NaN,NaN,NaN,웍스코어,NaN,NaN,NaN,NaN,0.000000,0.000000
26806050,3455119,GEN,Ncloud온라인회원,NaN,WORK2,NAVER WORKS,NOTE_TRIAL_USAGE,클로바노트 체험판,WORK2,NAVER WORKS,NOTE_TRIAL_USAGE,웍스 클로바노트 체험판,18551673,101820819,1,Korea,2,N,0.0,20250108,1.0,NaN,NaN,1.0,USAGE_DAY,사용 시간(일),CNT_T,3455119,2025.1.8,0,2025.1.8,NaN,N,2025.1.8,N,N,NaN,NaN,0.0,CNT_T,1.0,NaN,NaN,NaN,NaN,NaN,클로바노트,NaN,NaN,NaN,NaN,0.000000,0.000000
26806051,3455120,GEN,Ncloud온라인회원,NaN,WORK2,NAVER WORKS,CORE_TRIAL_USER_CNT,웍스 코어 체험판,WORK2,NAVER WORKS,CORE_TRIAL_USER_CNT,웍스 코어 체험판,18551686,101820956,1,Korea,2,N,0.0,20250108,1.0,NaN,NaN,1.0,USR_CNT,사용자 수,COR_T,3455120,2025.1.8,0,2025.1.8,NaN,N,2025.1.8,N,N,NaN,NaN,0.0,COR_T,1.0,NaN,NaN,NaN,NaN,NaN,웍스코어,NaN,NaN,NaN,NaN,0.000000,0.000000
26806052,3455121,GEN,Ncloud온라인회원,NaN,WORK2,NAVER WORKS,CORE_TRIAL_USER_CNT,웍스 코어 체험판,WORK2,NAVER WORKS,CORE_TRIAL_USER_CNT,웍스 코어 체험판,18551710,101821200,1,Korea,2,N,0.0,20250108,1.0,NaN,NaN,1.0,USR_CNT,사용자 수,COR_T,3455121,2025.1.8,0,2025.1.8,NaN,N,2025.1.8,N,N,NaN,NaN,0.0,COR_T,1.0,NaN,NaN,NaN,NaN,NaN,웍스코어,NaN,NaN,NaN,NaN,0.000000,0.000000